# Let's makes some Numpy Operations
In this notebook we will see different operation types that we can perform on arrays

## Exercise 1 Universal Functions
Given an ndarray x = [4, -1, 7, 9, 3, -5] compute the sigmoid function $ y = sigmoid(x)$ which maps numbers $(-\inf +\inf) \rightarrow (0,1)$

$$ sigmoid(x) = \frac{1}{1 + e^{-x}}$$

In [4]:
import numpy as np

def sigmoid(x):
    sig = 1/(1+np.exp(-x))
    return sig   
    
x = [4,-1,7,9,3,-5]
x = np.array(x)

print(sigmoid(x))


[0.98201379 0.26894142 0.99908895 0.99987661 0.95257413 0.00669285]


## Exercise 2 Aggregation functions
Given an array x = [[2, 3, -4,], [7, 5, 9]]

Return the mean of the elements along the rows and the minimum element along the columns

In [13]:
x = np.array([[2,3,-4],[7,5,9]])

print(x.mean(axis=-1))
print(x.mean(axis=0))

print(x.min(axis=-1))
print(x.min(axis=0))

[0.33333333 7.        ]
[4.5 4.  2.5]
[-4  5]
[ 2  3 -4]


## Exercise 3 Sorting
Given the same array as in Ex. 1, i.e., x = [4, -1, 7, 9, 3, -5], find the 3 highest values and the positions of the 2 lowest values

In [24]:
x = np.array([4, -1, 7, 9, 3, -5])

print(np.sort(x)[:-4:-1])
print(np.argsort(x)[:2])

[9 7 4]
[5 1]


# Exercise 4 Broadcasting
Compute the product between the array x1 = [[0,1,2], [3,4,5]] and the array x2 = [1, 2]
Does it raises an error? How shall x2 be modified to make the operation possible?


In [23]:
x1 = np.array([[0,1,2],[3,4,5]])
x2 = np.array([1,2])

#print(x1 * x2)

x3 = np.array([[1],[2]])
print(x1 * x3)

[[ 0  1  2]
 [ 6  8 10]]
