# Let's manipulate some arrays! 
In this notebook we will see different wasy in which we can manipulate an array

## Exercise 1 Array accessing 
Given an ndarray x = [[3.0, 2.0, 5.0], [1.0, 4.0, 2.0], [6.0, 7.0, 8.0]]
Return two arrays:
1) Compute the mean of the elements along the second column 
2) Retrieve the elements with values higher than 2 along the second and third rows 

In [24]:
import numpy as np
x = np.array([[3.0, 2.0, 5.0], 
              [1.0, 4.0, 2.0],
              [6.0, 7.0, 8.0]])

mean = np.mean(x[:, 1])
print(mean)
elems = x[1:, :]
print(elems[elems > 2])


4.333333333333333
[4. 6. 7. 8.]


## Exercise 2 Array accessing to update
Given the previous array x = [[3.0, 2.0, 5.0], [1.0, 4.0, 2.0], [6.0, 7.0, 8.0]]
1) set the values of the first column to 0, if they are greater than 2
2) then try to do the same for the first and third columns together. Does it work? 

In [23]:
x = np.array([[3.0, 2.0, 5.0], 
              [1.0, 4.0, 2.0],
              [6.0, 7.0, 8.0]])

mask = x[:,0] >  2
x[:, 0][mask] = 0
print("First update\n", x)

x = np.array([[3.0, 2.0, 5.0], 
              [1.0, 4.0, 2.0],
              [6.0, 7.0, 8.0]])
mask = x[:, [0,2]] > 2
x[:, [0,2]][mask] = 0#returns a copy
print("Second update\n", x)




First update
 [[0. 2. 5.]
 [1. 4. 2.]
 [0. 7. 8.]]
Second update
 [[3. 2. 5.]
 [1. 4. 2.]
 [6. 7. 8.]]


## Exercise 3 Array concatenation and reshaping
Given two arrays x1 = [[3,1], [2,4]] and x2 = [[3, 4], [2,4], [2,5]]

Try to concatenate them vertically and then horizontally
If something does not work try to reshape the arrays so that you can concatenate (or stack) them.


In [66]:
x1 = np.array([[3,1], [2,4]])
x2 = np.array([[3, 6], [8,7], [9,0]])
print("x1\n", x1)
print("x2\n", x2)

print("x1, x2 concatenation\n", np.concatenate((x1, x2)))

print("x1, x2 vstack\n", np.vstack((x1, x2))) # same result as above

# print(np.concatenate((x1,x2), axis=1)) # DOES NOT WORK: dimension along the axis of not concatenation must match!
# print(np.hstack((x1,x2))) # same as above

x3 = x2.reshape((2,3))
print("x3\n", x3)
print(np.concatenate((x1, x3),axis=1))

x1
 [[3 1]
 [2 4]]
x2
 [[3 6]
 [8 7]
 [9 0]]
x1, x2 concatenation
 [[3 1]
 [2 4]
 [3 6]
 [8 7]
 [9 0]]
x1, x2 vstack
 [[3 1]
 [2 4]
 [3 6]
 [8 7]
 [9 0]]
x3
 [[3 6 8]
 [7 9 0]]
[[3 1 3 6 8]
 [2 4 7 9 0]]
