# LAB #2: Numpy

## Introduction
In this laboratory, you will build your own version of the K-Nearest Neighbors algorithm (a.k.a. KNN) using
the NumPy library.
## 0 Preliminary steps
### 0.1 NumPy
Make sure you have the NumPy library installed, its use is strongly recommended for this laboratory.
NumPy is the fundamental package for scientific computing with Python. You can read more about it on
the official documentation.


In [2]:
import numpy as np

### 0.2 Iris dataset download 
For this lab, you will need two of the datasets you have already met: Iris and MNIST. Please refer to
Laboratory 1 for a complete description of the datasets.
Iris. You can download it from:
https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

## 1 Exercises 
Note that exercises marked with a ($\star$) are optional, you should focus on completing the other ones first.

## 1.1 Iris Analysis with Numpy
As you might remember from Lab. 1, the Iris dataset collects the measurements of different Iris flowers,
and each data point is characterized by 4 **features** (sepal length, sepal width, petal length, petal width) and is associated to 1 **label** (i.e. an Iris species - Setosa, Versicolor, or Virginica)  

1. Load the Iris dataset. You can use the `csv` library that we saw in the last laboratory or read it with the standard `open(filename, strategy)`. 
In the second case remember to split correctly the different fields, avoid new line characters. In any case check for empty lines. 
This time remember to store the 4 features in a numpy array `x` of shape (n_sample, 4) and the labels in a different array `y` of shape (n_sample,) converting the 3 different species to a corresponding numerical value. E.g.,
      - Iris-setosa: 0
      - Iris-versicolor: 1
      - Iris-virginica: 2

In [3]:
import csv
x = []
y = []
with open("iris.csv","r") as iris:
    for i,row in enumerate(csv.reader(iris)):
        if row == []:
            continue
        x.append(row[:-1])
        y.append(row[-1])
    x = np.array(x, dtype='float64')
    y = np.array(y)
    
    y[y == "Iris-setosa"] = 0
    y[y == "Iris-versicolor"] = 1
    y[y == "Iris-virginica"] = 2
    y=y.astype('int64')
    print(x)
    print(y)
          

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

2. Compute again the mean and standard deviation for each class by means of the numpy functions

In [4]:
means = [[],[],[]]
std_devs = [[],[],[]]
for j in range(3):
    for i in range(4):
        means[j].append(np.mean(x[np.argwhere(y==j), i]))
        std_devs[j].append(np.std(x[np.argwhere(y==j), i]))
print(means)
print(std_devs)

[[5.006, 3.418, 1.464, 0.244], [5.936, 2.7700000000000005, 4.26, 1.3259999999999998], [6.587999999999998, 2.974, 5.5520000000000005, 2.0260000000000002]]
[[0.3489469873777391, 0.37719490982779713, 0.17176728442867112, 0.10613199329137281], [0.5109833656783751, 0.31064449134018135, 0.4651881339845203, 0.19576516544063705], [0.6294886813914926, 0.3192553836664309, 0.546347874526844, 0.2718896835115301]]


3. Compute the distances among two samples (e.g., the $35^{th}$ and the $80^{th}$ and the $12^{th}$ and the $14^{th}$) 
by means of the 'np.linalg.norm' function which computes the euclidean distance. 
  - Can you guess if the two couples of samples belong to the same species?
  - From the mean and standard deviations computed before can you guess which species? 

In [5]:
def norm(s1,s2):
    return np.linalg.norm(x[s1]-x[s2])

norm(35,80)

2.908607914449797

## 1.2 KNN design and implementation
In this exercise, you will implement your own version of the K-Nearest Neighbors (KNN) algorithm, and you will use it to assign an
Iris species (i.e. a label) to flowers whose species is unknown.

The KNN algorithm is straightforward. Suppose that some measurements (e.g., the iris features) and their
relative label (e.g., the iris species) of a set of samples are known in advance. 

<img src="https://mlarchive.com/wp-content/uploads/2022/09/img2.png" width="800">

Then, whenever we want to label a new sample, we look at the K most similar points (a.k.a. neighbors) and assign a label accordingly. 

<img src="https://mlarchive.com/wp-content/uploads/2022/09/img1-1.png" width="800">


The simplest solution is using a majority voting scheme: if the majority of the neighbors votes for a label, we will go for it. 
This approach is naive only at first sight: the local similarity assumed by KNN happens to be roughly true. 
Even though this reasoning does not generalize well, the KNN provides a valid baseline for your tasks.




1. Let’s identify a portion of our data for which we will try to guess the species. Randomly select 20%
of the records and store the first four columns (i.e. the features representing each flower) into a
two-dimensional numpy array of shape ($N_{test} \times 4$), you can call it `X_test` and $N_{test}$ is the 20% of the total number of samples.
For the same records, store the test label column (i.e. the one with the species values) into another array, namely `y_test`. 
This is the data that will be used to test the accuracy of your KNN implementation and its correct functioning (i.e. the testing data).

In [6]:
indices = np.arange(150)
np.random.shuffle(indices)
train_len = 80*len(indices) // 100
test_idx = indices[train_len:]

X_test = x[test_idx]
y_test = y[test_idx]
print(X_test)
print(y_test)

[[5.6 2.7 4.2 1.3]
 [5.8 2.6 4.  1.2]
 [7.6 3.  6.6 2.1]
 [5.7 2.5 5.  2. ]
 [6.9 3.1 4.9 1.5]
 [5.2 4.1 1.5 0.1]
 [6.  3.  4.8 1.8]
 [6.  2.2 4.  1. ]
 [5.9 3.  4.2 1.5]
 [6.2 2.8 4.8 1.8]
 [6.7 3.1 5.6 2.4]
 [4.3 3.  1.1 0.1]
 [6.6 3.  4.4 1.4]
 [6.9 3.2 5.7 2.3]
 [6.1 2.8 4.  1.3]
 [7.7 3.  6.1 2.3]
 [4.7 3.2 1.3 0.2]
 [6.5 3.2 5.1 2. ]
 [6.3 2.5 4.9 1.5]
 [4.6 3.4 1.4 0.3]
 [5.  2.  3.5 1. ]
 [5.1 3.5 1.4 0.3]
 [5.4 3.7 1.5 0.2]
 [4.4 3.2 1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.8 3.4 1.6 0.2]
 [5.6 3.  4.5 1.5]
 [7.7 3.8 6.7 2.2]
 [5.  3.5 1.3 0.3]
 [5.7 2.8 4.1 1.3]]
[1 1 2 2 1 0 2 1 1 2 2 0 1 2 1 2 0 2 1 0 1 0 0 0 0 0 1 2 0 1]


2. Store the remaining 80% of the records in the same way. In this case, use the names X_train andy_train for the arrays.
This is the data that your model will use as ground-truth knowledge (i.e. the training data, from which we extract the knowledge and that we will use for comparison).


In [7]:
train_idx = indices[:train_len]
X_train = x[train_idx]
y_train = y[train_idx]
print(X_train)
print(y_train)

[[5.4 3.9 1.7 0.4]
 [7.2 3.2 6.  1.8]
 [5.9 3.2 4.8 1.8]
 [5.1 3.5 1.4 0.2]
 [4.9 2.5 4.5 1.7]
 [5.4 3.  4.5 1.5]
 [6.9 3.1 5.1 2.3]
 [6.7 3.  5.  1.7]
 [5.  3.3 1.4 0.2]
 [5.8 2.7 3.9 1.2]
 [6.7 3.1 4.7 1.5]
 [5.1 2.5 3.  1.1]
 [7.2 3.  5.8 1.6]
 [5.7 2.6 3.5 1. ]
 [6.3 2.9 5.6 1.8]
 [5.7 4.4 1.5 0.4]
 [7.1 3.  5.9 2.1]
 [5.2 3.4 1.4 0.2]
 [5.  3.6 1.4 0.2]
 [6.8 3.2 5.9 2.3]
 [5.3 3.7 1.5 0.2]
 [6.3 3.3 4.7 1.6]
 [6.5 3.  5.5 1.8]
 [5.  3.5 1.6 0.6]
 [6.2 3.4 5.4 2.3]
 [6.2 2.2 4.5 1.5]
 [5.  2.3 3.3 1. ]
 [4.9 3.1 1.5 0.1]
 [6.3 2.8 5.1 1.5]
 [6.8 2.8 4.8 1.4]
 [6.4 2.7 5.3 1.9]
 [4.7 3.2 1.6 0.2]
 [5.1 3.4 1.5 0.2]
 [5.8 2.7 5.1 1.9]
 [4.9 3.1 1.5 0.1]
 [4.9 2.4 3.3 1. ]
 [4.8 3.1 1.6 0.2]
 [5.5 4.2 1.4 0.2]
 [5.5 3.5 1.3 0.2]
 [7.7 2.8 6.7 2. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [6.7 3.1 4.4 1.4]
 [6.4 3.2 4.5 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 2.8 4.9 2. ]
 [6.4 3.1 5.5 1.8]
 [6.1 3.  4.6 1.4]
 [6.7 3.3 5.7 2.1]
 [4.8 3.  1.4 0.1]
 [6.3 2.5 5.  1.9]
 [6.1 2.8 4.7 1.2]
 [5.4 3.9 1.

3. Focus now on the KNN technique. 
From the next month, you will use the `scikit-learn` package. Many of its functionalities
are exposed via an object-oriented interface. With this paradigm in mind, implement now the KNN
algorithm and expose it as a Python class. The bare skeleton of your class should look like this (you
are free to add other methods if you want to).

```
class KNearestNeighbors:
    def __init__(self, k):
        self.k = k
    def fit(self, X, y):
        """
        Store the 'prior knowledge' of you model that will be used
        to predict new labels.
        :param X : input data points, ndarray, shape = (R,C).
        :param y : input labels, ndarray, shape = (R,).
        """
        pass # TODO: implement it!
    
    def predict(self, X):
        """Run the KNN classification on X.
        :param X: input data points, ndarray, shape = (N,C).
        :return: labels : ndarray, shape = (N,).
        """
        pass # TODO: implement it!

```


Implement the fit method first. Here, you should only keep track of the main attributes that will be used by the algorithm.
In this version of the algorithm, does the KNN need to store all the samples of `X_train` and `y_train`?

In [8]:
#yes

4. Implement the `predict` method. The function receives as input a numpy array with N rows and C
columns, corresponding to N flowers. The method assigns to each row one of the three Iris species 
using the KNN algorithm, and returns the predicted species as a numpy array. For the actual implementation, apply
the identify K neighbors using the euclidean distance specified by the parameters k.
Then, assign the label using a majority voting scheme


In [16]:
class KNearestNeighbors:
    def __init__(self, k):
        self.k = k
    def fit(self, X, y):
        self.X_train=X
        self.y_train=y
    
    def predict(self, X):
        out = []
        for i in range(len(X)):
            fdist = []
            votes = []
            for j in range(len(X_train)):
                dist = np.linalg.norm(self.X_train[j]-X[i])
                fdist.append([dist, j])
            fdist.sort()
            fdist = fdist[0:self.k]
            for d,j in fdist:
                votes.append(y_train[j])
            print(votes)
            out.append(max(votes))
        return np.array(out)
    
    def accuracy(self, X_test, y_test):
        y_pred = self.predict(X_test)
        print(f"Accuracy score: {(y_pred==y_test).sum()/len(y_test)}")
        
KNN = KNearestNeighbors(1)
KNN.fit(X_train,y_train)

print(KNN.predict(X_test))

[1]
[1]
[2]
[2]
[1]
[0]
[2]
[1]
[1]
[2]
[2]
[0]
[1]
[2]
[1]
[2]
[0]
[2]
[2]
[0]
[1]
[0]
[0]
[0]
[0]
[0]
[1]
[2]
[0]
[1]
[1 1 2 2 1 0 2 1 1 2 2 0 1 2 1 2 0 2 2 0 1 0 0 0 0 0 1 2 0 1]


5. Now let’s fit the KNN model with the X_train and y_train data. Then, try to use your KNN model
to predict the species for each record in X_test and store them in a nupy array called y_pred.
As we did in the previous lab, check how many Iris species in the array y_pred have been guessed correctly computing with respect to the ones in y_test computing the accuracy. 
A prediction is correct if `y_pred[i] == y_test[i]`. To get the accuracy then compute the ratio between the number of correct guesses and the total number of guesses is known. 
If all labels are assigned correctly ((y_pred == y_test).all() == True), the accuracy of the model is 100%. 
Instead, if none of the guessed species corresponds to the real one ((y_pred == y_test).any() == False), the accuracy is 0%


In [17]:
KNN.accuracy(X_test, y_test)

[1]
[1]
[2]
[2]
[1]
[0]
[2]
[1]
[1]
[2]
[2]
[0]
[1]
[2]
[1]
[2]
[0]
[2]
[2]
[0]
[1]
[0]
[0]
[0]
[0]
[0]
[1]
[2]
[0]
[1]
Accuracy score: 0.9666666666666667


6. ($\star$) As a software developer, you might want to increase the functionalities of your product and
publish newer versions over time. The better your code is structured and organized, the lower is the
effort to release updates.
As such,  extend your KNN implementation adding the parameter `distance`. This has to be one among:
    - Euclidean distance: $ euclidean(p,q) = \sqrt{\sum_{i=1}^{n} (p_i _- q_i)^2} $
    - Manhattan distance: $ manhattan(p,q) = \sum_{i=1}^n |p_i - q_i|$
    - Cosine distance: $ cosine(p, q) = \frac{\sum_{i=1}^n p_i q_i}{ \sqrt{\sum^n_{i=1}} p^2_i \cdot \sqrt{\sum^n_{i=1} q_i^2}}$

If any of this distance is not already implemented in `numpy` implement it yourself

In [62]:
from scipy.spatial import distance as ss
class KNearestNeighbors:
    def __init__(self, k):
        self.k = k
    def fit(self, X, y):
        self.X_train=X
        self.y_train=y
        
    def distance(self,opt,x,y):
        if opt==0:
            return np.linalg.norm(x-y)
        if opt == 1:
            return abs(x-y).sum()
        if opt == 2:
         return ss.cosine(x,y)
    
    def predict(self, X, opt):
        out = []
        for i in range(len(X)):
            fdist = []
            votes = []
            for j in range(len(X_train)):
                dist = self.distance(opt,self.X_train[j],X[i])
                fdist.append([dist, j])
            fdist.sort()
            fdist = fdist[0:self.k]
            for d,j in fdist:
                votes.append(y_train[j])
            out.append(max(votes))
        return np.array(out)
    
    def accuracy(self, X_test, y_test, opt):
        y_pred = self.predict(X_test, opt)
        print(y_pred)
        print(f"Accuracy score: {(y_pred==y_test).sum()/len(y_test)}")
        
KNN = KNearestNeighbors(3)
KNN.fit(X_train,y_train)
'''
0 - euclidean distance
1 - manhattan distance 
2 - cosine distance
'''
KNN.accuracy(X_test, y_test, 2)

[1 1 2 2 1 0 2 1 1 2 2 0 1 2 1 2 0 2 2 0 1 0 0 0 0 0 1 2 0 1]
Accuracy score: 0.9666666666666667



7. ($\star$) Again, extend now your KNN implementation by adding the parameter `weights` to the constructor,
as shown below:

```
class KNearestNeighbors:
def __init__(self, k, distance_metric="euclidean", weights="uniform"):
self.k = k
self.distance_metric = distance_metric
self.weights = weights
```

Change your KNN implementation to accept a new weighting scheme for the labels. If weights=
"distance", weight neighbor votes by the inverse of their distance (for the distance, again, use
distance_metric). The weight for a neighbor of the point p is:

$
w(p, n) = \frac{1}{distance\_metric(p, n)}
$

Instead, if the default is chosen (weights="uniform"), use the majority voting you already implemented
in Exercise 6.

<img src="https://mlarchive.com/wp-content/uploads/2022/09/img5.png">


In [76]:
from scipy.spatial import distance as ss
class KNearestNeighbors1:
    def __init__(self, k, distance_metric="euclidean", weights="uniform"):
        self.k = k
        self.distance_metrics=distance_metric.lower()
        self.weights=weights
        
    def fit(self, X, y):
        self.X_train=X
        self.y_train=y
        
    def distance(self,x,y):
        try:
            dist = 0
            if self.distance_metrics == 'euclidean':
                return np.linalg.norm(x-y)
            if self.distance_metrics == 'manhattan':
                return abs(x-y).sum()
            if self.distance_metrics == 'cosine':
             return ss.cosine(x,y)
        except:
            print("No valid distance\n")
            quit()
    
    def predict(self, X):
        out = []
        for i in range(len(X)):
            fdist = []
            votes = []
            for j in range(len(X_train)):
                if self.weights == 'uniform': weight = self.distance(self.X_train[j],X[i])
                else: weight = 1/self.distance(self.X_train[j],X[i])
                fdist.append([weight, j])
            fdist.sort()
            fdist = fdist[0:self.k]
            for d,j in fdist:
                votes.append(y_train[j])
            out.append(max(votes))
        return np.array(out)
    
    def accuracy(self, X_test, y_test):
        y_pred = self.predict(X_test)
        print(y_pred)
        print(y_pred==y_test)
        print(f"Accuracy score: {(y_pred==y_test).sum()/len(y_test)}")
        
KNN = KNearestNeighbors1(3,"cosine", "distance")
KNN.fit(X_train,y_train)
'''
0 - euclidean distance
1 - manhattan distance 
2 - cosine distance
'''
KNN.accuracy(X_test, y_test)

[0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 2 0 0 2 0 2 2 2 2 2 0 0 2 0]
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False]
Accuracy score: 0.0


8. ($\star$) Test the modularity of the implementation applying it on a different dataset. Ideally, you should
not change the code of your KNN python class.
- Download the MNIST dataset and sample only 100 points per digit. You will end up with a dataset of 1000 samples.
- Define again four numpy arrays as you did in Exercises 2 and 3.
- Apply your KNN as you did for the Iris dataset.
- Evaluate the accuracy on MNIST’s y_test.